package monitoring

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// RequestsTotal counts API requests by method, path, and status code.
	RequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: "little_tyke",
		Subsystem: "http",
		Name:      "requests_total",
		Help:      "Total number of HTTP requests.",
	}, []string{"method", "path", "status"})

	// RequestDuration observes request duration in seconds.
	RequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: "little_tyke",
		Subsystem: "http",
		Name:      "request_duration_seconds",
		Help:      "Duration of HTTP requests in seconds.",
		Buckets:   []float64{0.1, 0.5, 1, 2.5, 5, 10, 30, 60, 120},
	}, []string{"method", "path"})

	// TokensGenerated counts tokens produced by the model.
	TokensGenerated = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: "little_tyke",
		Subsystem: "model",
		Name:      "tokens_generated_total",
		Help:      "Total tokens generated by the model.",
	})

	// TokensPerSecond tracks generation speed.
	TokensPerSecond = promauto.NewHistogram(prometheus.HistogramOpts{
		Namespace: "little_tyke",
		Subsystem: "model",
		Name:      "tokens_per_second",
		Help:      "Model generation speed in tokens per second.",
		Buckets:   []float64{1, 5, 10, 15, 20, 30, 40, 50, 75, 100},
	})
)
